#!/usr/bin/env bash
# Pacman alias wrapper for kori
# Requires: pacaur

if [[ -n "$1" ]]; then
	case "$1" in
		"install")
			shift 1
			if [[ -n "$1" ]]; then
				pacaur -S $@
			else
				echo "Error! You have to specify a package to install!"
				exit 1
			fi
		;;
		"purge")
			shift 1
                        if [[ -n "$1" ]]; then
                                pacaur -Rcns $@
                        else
                                echo "Error! You have to specify a package to remove and purge!"
                                exit 1
                        fi
		;;
		"search")
			shift 1
                        if [[ -n "$1" ]]; then
                                pacaur -Ss $@
                        else
                                echo "Error! You must specify a search term!"
                                exit 1
                        fi
		;;
		"upgrade") pacaur -Syu;;
		"clean") pacaur -Sc;;
		*) pacaur "${@}";;
		# *) echo 'Error! Improper command. Please use one of the following: install, purge, search, upgrade, clean.'; exit 1;;
	esac
else
	echo "Error! You gotta specify a command, silly!"
	exit 1
fi

