#!/usr/bin/env bash
# pomf.se uploader
# requires: curl
 
dest_url='http://pomf.se/new/up.php'
return_url='http://a.pomf.se'
 
if [[ -n "${1}" ]]; then
file="${1}"
if [ -f ${file} ]; then
printf "Uploading ${file}..."
my_output=$(curl --silent -F qqfile="@${file}" "${dest_url}")
if [[ "${my_output}" =~ '"success":true,' ]]; then
return_file=$(echo "$my_output" | awk -F '"' '{print $6}')
printf 'done.\n'
printf "File can be found at: ${return_url}/${return_file}.\n"
else
printf 'Error! File not uploaded.\n'
exit 1
fi
else
printf 'Error! File does not exist!\n'
exit 1
fi
else
printf 'Error! You must supply a filename to upload!\n'
exit 1
fi
